env: gridworld4
env_args:
  input_rows: 7
  input_cols: 7
  num_pairs: 2
  map_name: "swap"
  episode_limit: 50
  obs_type: "mark"  # "mark" for fully obs
  path: Null

learner_log_interval: 1000
log_interval: 1000
runner_log_interval: 1000
t_max: 1005000
test_interval: 1000
test_nepisode: 30
test_greedy: True
demo_interval: 1000

save_model: False
use_tensorboard: True
save_model_interval: 20000
