env: gridworld5
env_args:
  n_agents: 3
  input_rows: 4
  input_cols: 4
  map_name: "seperate"
  penalty: True
  penalty_amount: 0.1
  visibility: 2
  path: Null

learner_log_interval: 1000
log_interval: 1000
runner_log_interval: 1000
t_max: 505000
test_interval: 1000
test_nepisode: 30
test_greedy: True
demo_interval: 1000

save_model: False
use_tensorboard: True
save_model_interval: 20000

